### ISSUE TITLE
Keybinds are broken

### ISSUE THREAD

**Issue by DuncanLarsen** [squeeglii/grapplemod#2] opened 2023-02-03 19:16 UTC
Something about the way this mod implements keybinds is broken. Rebound actions like sneak trigger off of their default keys. Also seems to affect mod-added actions.

**Comment by DuncanLarsen** [comment] 2023-02-04 07:20
Realized I forgot to provide details about version. This occurred on 1.19.3

**Comment by squeeglii** [comment] 2023-02-06 20:01
I could understand it breaking with how keybindings are implemented. To replace the original mod's behaviour, multiple action can have the same key bound and both still work.

As of 1.19.3, however, I cannot reproduce the following:

> Rebound actions like sneak trigger off of their default keys

- I rebound vanilla's Sneak to right-shift
- Pressed left-shift (no result, did not crouch)
- Pressed right-shift (result, did crouch)

Are there any other mods installed that could create the issue when *combined* with this mod?

**Comment by squeeglii** [comment] 2023-02-07 02:10
I recommend checking again with v1.3 as well ^

**Comment by StormRider1224** [comment] 2023-02-16 03:01
using 1.19.2 and i also have broken keybinds issue, definitly this mod had to comb through a bunch, issue consists of all keybinds being rebind able but retains original bind making the new bind irrelavant and also resulting in multiple default binds on the same key an issue as they are not able to be rebound completely such as walk forward default w changed to up arrow allows walking forward with both keys when intended function only supposed to be up arrow, changing back does not make it stick to up arrow only default keys, shits baffling lol

**Comment by StormRider1224** [comment] 2023-02-16 03:05
> using 1.19.2 and i also have broken keybinds issue, definitly this mod had to comb through a bunch, issue consists of all keybinds being rebind able but retains original bind making the new bind irrelavant and also resulting in multiple default binds on the same key an issue as they are not able to be rebound completely such as walk forward default w changed to up arrow allows walking forward with both keys when intended function only supposed to be up arrow, changing back does not make it stick to up arrow only default keys, shits baffling lol

not sure what it conflicts with but with only this mod and req issue does not occur will get back when i figure out what is conflicting

**Comment by StormRider1224** [comment] 2023-02-16 03:32
> 
wierdest conflict but this mod https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric 
is the conflict in my list, adding it in created the issue even with only both mods reqirements

**Comment by squeeglii** [comment] 2023-02-16 03:37
Still can't reproduce the issue - it's confusing. My best guess would still be a mod incompatibility when the keybind magic of this mod messes with logic in another mod? 

Are you able to provide a full mod list where this mod still experiences the issue?

> Using the example with "Walk Forwards", replacing 'w' with 'Up Arrow'

I've tested it with:
- a dev environment
- a regular client
- fabric
- quilt
- all currently supported versions (1.18.2 -> 1.19.3)

**Comment by squeeglii** [comment] 2023-02-16 03:37
> wierdest conflict but this mod https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric is the conflict in my list, adding it in created the issue even with only both mods reqirements

oh wait I missed that - I shall have a look with it

**Comment by StormRider1224** [comment] 2023-02-16 03:40
> > wierdest conflict but this mod https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric is the conflict in my list, adding it in created the issue even with only both mods reqirements
> 
> oh wait I missed that - I shall have a look with it

np yeah just this mod and that and the requirements on both mods and it created the issue mind you i am on 1.19.2

**Comment by squeeglii** [comment] 2023-02-16 03:47
Hey, would you look at that! Reproduced the issue on 1.19.3! - I'll look into it. Thank you ^^

**Comment by StormRider1224** [comment] 2023-02-16 03:48
no problem glad to help!!

**Comment by squeeglii** [comment] 2023-02-27 22:42
Fixed as of [9376ddf](https://github.com/CloudG360/grapplemod-restitched/commit/9376ddf3be7ef0d105676ac82818eee949a6ea52) - Will be in a hotfix real soon!

**Closed as completed by squeeglii** 2023-02-27 22:42 UTC
Labels: bug
