### ISSUE TITLE
breaks right click interactions

### ISSUE THREAD

**Issue by inikishev** [squeeglii/grapplemod#6] opened 2023-02-11 16:41 UTC
**Describe the bug**
when I press right click on doors/fence gates with this mod enabled, it presses the open sound but doesn't open. Only opens when I hold right click. Without this mod it works

**Version**
Include the versions for:
- The Grapple Hook Mod 1.19.2-v1.3
- The Mod Loader (fabric/quilt - include the api mod's version) fabric 0.73.2+1.19.2
- Minecraft 1.19.2

**Output Log**
https://gist.github.com/stunlocked1/2ca25140da64373570f4a44e0d6897b7

**To Reproduce**
click on door

**Comment by squeeglii** [comment] 2023-02-11 17:04
Unable to reproduce with just the base mod - marking it as a mod incompatibility

**Comment by squeeglii** [comment] 2023-02-11 17:27
Are you running a mod pack? It would be useful if all the mods were collected in one place for testing.

**Comment by squeeglii** [comment] 2023-02-27 20:21
The bug's behaviour aligns with Issues #8 and #10 - possibly linked?

**Comment by squeeglii** [comment] 2023-02-27 22:41
Assumed to be fixed as of [9376ddf](https://github.com/CloudG360/grapplemod-restitched/commit/9376ddf3be7ef0d105676ac82818eee949a6ea52) 

Try testing it again with v1.4 once it's published.

**Closed as completed by squeeglii** 2023-02-27 22:41 UTC
Labels: fixed?, mod-incompatibility
